### ISSUE TITLE
i was looking for a database migration tool for our project

### ISSUE THREAD

**Issue by MahdiZareie** [s-soroosh/azma-py#8]
what you think about having a migration tool for our project to keep records of db changes ?
i find this : http://south.aeracode.org/ and i think it can help

**Comment by s-soroosh** [comment]
Yes that's OK but i had problem to use simultaneously with pycharm, because pycharm task was not able to find its tasks.
I had some misconfiguration in my pycharm and i could solve it. I have committed it so we can use it.
By the way django 1.7 will have it out of the box.

Thank you for your good suggestion

**Comment by s-soroosh** [comment]
Please close completed issues, thanks.
