### ISSUE TITLE
app with HTML UI vs app without HTML UI

### ISSUE THREAD

**Issue by MahdiZareie** [s-soroosh/azma-py#9]
we have put homepage in 'exam' application while wage_meter is another app itself so for implementing wage_mete app i found two different solutions : 
- the first way is to create UI within app completely standalone and then in homepage we can use <a href='https://docs.djangoproject.com/en/1.6/howto/custom-template-tags/#inclusion-tags'>Inclusion tags </a> to partially load UI from another app (wage_meter) 
- the second way is to create our wage_meter without any pre built UI, in this case wage_meter's Responses will be Json instead of HTML .
  if we choose second way we have to build UI somewhere else (like our Homepage template)

note : there is another implementation for first approach , which we don't use <a href='https://docs.djangoproject.com/en/1.6/howto/custom-template-tags/#inclusion-tags'>Inclusion tags </a> and instead using client side methods like <iframe> or Jquery.get in our homepage in order to load another template.

**Comment by s-soroosh** [comment]
there is no problem with including the first page from wage meter project nad i think it needs less effort from the other solutions

Sent from Samsung Mobile

 MahdiZareie notifications@github.com wrote: 

we have put homepage in 'exam' application and wage_meter is another app itself so for implementing wage_mete app i found two different solutions :

the first way is to create UI within app completely standalone and then in homepage we can use Inclusion tags to partially load UI from another app (wage_meter)

the second way is to create our wage_meter without any pre built UI, in this case wage_meter's Responses will be Json instead of HTML .
if we choose second way we have to build UI somewhere else (like our Homepage template)

note : there is another implementation for first approach , which we don't use Inclusion tags and instead using client side methods like or Jquery.get in our homepage in order to load another template.

**Comment by s-soroosh** [comment]
Please close completed issues, thanks.
